# Generated by Django 3.1.3 on 2021-08-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicted_score',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk10',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk11',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk12',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk13',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk14',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk15',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk16',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk17',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk18',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk3',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk4',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk5',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk6',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk7',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk8',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Hawk_Wk9',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk1',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk10',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk11',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk12',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk13',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk14',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk15',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk16',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk17',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk18',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk2',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk3',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk4',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk5',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk6',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk7',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk8',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='Opp_Wk9',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='predicted_score',
            name='author',
            field=models.CharField(max_length=420, null=True, unique=True),
        ),
    ]
