# Generated by Django 3.1.3 on 2021-08-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0002_auto_20210824_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicted_score',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
