# Generated by Django 3.1.3 on 2021-07-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nfl_teams',
            fields=[
                ('team_name', models.CharField(max_length=420)),
                ('team_acronym', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='predicted_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=420)),
                ('Hawk_Wk1', models.PositiveIntegerField(default=0)),
                ('Opp_Wk1', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk2', models.PositiveIntegerField(default=0)),
                ('Opp_Wk2', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk3', models.PositiveIntegerField(default=0)),
                ('Opp_Wk3', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk4', models.PositiveIntegerField(default=0)),
                ('Opp_Wk4', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk5', models.PositiveIntegerField(default=0)),
                ('Opp_Wk5', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk6', models.PositiveIntegerField(default=0)),
                ('Opp_Wk6', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk7', models.PositiveIntegerField(default=0)),
                ('Opp_Wk7', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk8', models.PositiveIntegerField(default=0)),
                ('Opp_Wk8', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk9', models.PositiveIntegerField(default=0)),
                ('Opp_Wk9', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk10', models.PositiveIntegerField(default=0)),
                ('Opp_Wk10', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk11', models.PositiveIntegerField(default=0)),
                ('Opp_Wk11', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk12', models.PositiveIntegerField(default=0)),
                ('Opp_Wk12', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk13', models.PositiveIntegerField(default=0)),
                ('Opp_Wk13', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk14', models.PositiveIntegerField(default=0)),
                ('Opp_Wk14', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk15', models.PositiveIntegerField(default=0)),
                ('Opp_Wk15', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk16', models.PositiveIntegerField(default=0)),
                ('Opp_Wk16', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk17', models.PositiveIntegerField(default=0)),
                ('Opp_Wk17', models.PositiveIntegerField(default=0)),
                ('Hawk_Wk18', models.PositiveIntegerField(default=0)),
                ('Opp_Wk18', models.PositiveIntegerField(default=0)),
                ('Submitted_Date', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerage.nfl_teams')),
            ],
        ),
    ]
